version: '3.1'
services:
  db:
    image: mariadb
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: whack
    volumes:
      - db:/var/lib/mysql
    ports:
      - 3306:3306

volumes:
  db: